### ISSUE TITLE
Content on radixproject.org is inconsistent with Privacy Policy

### ISSUE THREAD

**Issue by ghost** [theradixproject/radixproject.org#2]
### Actual behavior

Radix's Privacy Policy states,

> "We will comply with the law & share any data necessary in the event of a subpoena, legal request or any other matter where the law dictates we share our information with the authorities."

https://github.com/theradixproject/radixproject.org/blob/2e4e7dea6783f90553e1d47e4a2c30b19cc17b18/src/routes/privacy/%2Bpage.mdx?plain=1#L38-L40

However, `index.html` in the root misleadingly claims,

>"We will never share confidential or sensitive information with third parties, so you can rest assured that your valuable project infrastructure is in trustworthy hands."

https://github.com/theradixproject/radixproject.org/blob/2e4e7dea6783f90553e1d47e4a2c30b19cc17b18/src/components/LeftRight.svelte#L29-L31

### Expected behavior

The statements in `index.html` should be consistent with the Privacy Policy.
Inserting phrases such as "Radix's Privacy Policy describes how Radix shares confidential or sensitive information with third parties" before the misleading claim could better emphasize that Radix takes privacy seriously.

### Steps to reproduce

Browse https://radixproject.org/ and https://radixproject.org/privacy.
Notice the inconsistent and misleading claim.
The archives are:
https://archive.ph/LuUZF
https://web.archive.org/web/20221204031634/https://radixproject.org/.

**Comment by ghost** [comment]
The claim "We will never share confidential or sensitive information with third parties" on https://radixproject.org/ is hardly justified. Regular publication of the [transparency report](https://en.wikipedia.org/wiki/Transparency_report) and [warrant canary](https://en.wikipedia.org/wiki/Warrant_canary) would be beneficial.

**Comment by gianni-rosato** [comment]
673ea6f319ce04a228fe730bcc9ac9fd91254ea0
